export interface Country {
  code: string
  name: string
  flag: string
}

/**
 * List of countries with their code, name, and flag
 */
export const COUNTRIES: Country[] = [
  { code: 'us', name: 'United States', flag: 'us' },
  { code: 'gb', name: 'United Kingdom', flag: 'gb' },
  { code: 'ca', name: 'Canada', flag: 'ca' },
  { code: 'au', name: 'Australia', flag: 'au' },
  { code: 'de', name: 'Germany', flag: 'de' },
  { code: 'fr', name: 'France', flag: 'fr' },
  { code: 'es', name: 'Spain', flag: 'es' },
  { code: 'it', name: 'Italy', flag: 'it' },
  { code: 'pt', name: 'Portugal', flag: 'pt' },
  { code: 'nl', name: 'Netherlands', flag: 'nl' },
  { code: 'be', name: 'Belgium', flag: 'be' },
  { code: 'ch', name: 'Switzerland', flag: 'ch' },
  { code: 'at', name: 'Austria', flag: 'at' },
  { code: 'se', name: 'Sweden', flag: 'se' },
  { code: 'no', name: 'Norway', flag: 'no' },
  { code: 'dk', name: 'Denmark', flag: 'dk' },
  { code: 'fi', name: 'Finland', flag: 'fi' },
  { code: 'pl', name: 'Poland', flag: 'pl' },
  { code: 'cz', name: 'Czech Republic', flag: 'cz' },
  { code: 'hu', name: 'Hungary', flag: 'hu' },
  { code: 'ro', name: 'Romania', flag: 'ro' },
  { code: 'bg', name: 'Bulgaria', flag: 'bg' },
  { code: 'hr', name: 'Croatia', flag: 'hr' },
  { code: 'si', name: 'Slovenia', flag: 'si' },
  { code: 'sk', name: 'Slovakia', flag: 'sk' },
  { code: 'lt', name: 'Lithuania', flag: 'lt' },
  { code: 'lv', name: 'Latvia', flag: 'lv' },
  { code: 'ee', name: 'Estonia', flag: 'ee' },
  { code: 'ie', name: 'Ireland', flag: 'ie' },
  { code: 'is', name: 'Iceland', flag: 'is' },
  { code: 'mt', name: 'Malta', flag: 'mt' },
  { code: 'cy', name: 'Cyprus', flag: 'cy' },
  { code: 'gr', name: 'Greece', flag: 'gr' },
  { code: 'mx', name: 'Mexico', flag: 'mx' },
  { code: 'br', name: 'Brazil', flag: 'br' },
  { code: 'ar', name: 'Argentina', flag: 'ar' },
  { code: 'cl', name: 'Chile', flag: 'cl' },
  { code: 'co', name: 'Colombia', flag: 'co' },
  { code: 'pe', name: 'Peru', flag: 'pe' },
  { code: 've', name: 'Venezuela', flag: 've' },
  { code: 'ec', name: 'Ecuador', flag: 'ec' },
  { code: 'uy', name: 'Uruguay', flag: 'uy' },
  { code: 'py', name: 'Paraguay', flag: 'py' },
  { code: 'bo', name: 'Bolivia', flag: 'bo' },
  { code: 'gy', name: 'Guyana', flag: 'gy' },
  { code: 'sr', name: 'Suriname', flag: 'sr' },
  { code: 'fj', name: 'Fiji', flag: 'fj' },
  { code: 'nz', name: 'New Zealand', flag: 'nz' },
  { code: 'jp', name: 'Japan', flag: 'jp' },
  { code: 'kr', name: 'South Korea', flag: 'kr' },
  { code: 'cn', name: 'China', flag: 'cn' },
  { code: 'tw', name: 'Taiwan', flag: 'tw' },
  { code: 'hk', name: 'Hong Kong', flag: 'hk' },
  { code: 'sg', name: 'Singapore', flag: 'sg' },
  { code: 'my', name: 'Malaysia', flag: 'my' },
  { code: 'th', name: 'Thailand', flag: 'th' },
  { code: 'vn', name: 'Vietnam', flag: 'vn' },
  { code: 'ph', name: 'Philippines', flag: 'ph' },
  { code: 'id', name: 'Indonesia', flag: 'id' },
  { code: 'in', name: 'India', flag: 'in' },
  { code: 'pk', name: 'Pakistan', flag: 'pk' },
  { code: 'bd', name: 'Bangladesh', flag: 'bd' },
  { code: 'lk', name: 'Sri Lanka', flag: 'lk' },
  { code: 'np', name: 'Nepal', flag: 'np' },
  { code: 'bt', name: 'Bhutan', flag: 'bt' },
  { code: 'mm', name: 'Myanmar', flag: 'mm' },
  { code: 'kh', name: 'Cambodia', flag: 'kh' },
  { code: 'la', name: 'Laos', flag: 'la' },
  { code: 'mn', name: 'Mongolia', flag: 'mn' },
  { code: 'kz', name: 'Kazakhstan', flag: 'kz' },
  { code: 'uz', name: 'Uzbekistan', flag: 'uz' },
  { code: 'kg', name: 'Kyrgyzstan', flag: 'kg' },
  { code: 'tj', name: 'Tajikistan', flag: 'tj' },
  { code: 'tm', name: 'Turkmenistan', flag: 'tm' },
  { code: 'af', name: 'Afghanistan', flag: 'af' },
  { code: 'ir', name: 'Iran', flag: 'ir' },
  { code: 'iq', name: 'Iraq', flag: 'iq' },
  { code: 'sy', name: 'Syria', flag: 'sy' },
  { code: 'lb', name: 'Lebanon', flag: 'lb' },
  { code: 'jo', name: 'Jordan', flag: 'jo' },
  { code: 'il', name: 'Israel', flag: 'il' },
  { code: 'ps', name: 'Palestine', flag: 'ps' },
  { code: 'sa', name: 'Saudi Arabia', flag: 'sa' },
  { code: 'ae', name: 'United Arab Emirates', flag: 'ae' },
  { code: 'qa', name: 'Qatar', flag: 'qa' },
  { code: 'kw', name: 'Kuwait', flag: 'kw' },
  { code: 'bh', name: 'Bahrain', flag: 'bh' },
  { code: 'om', name: 'Oman', flag: 'om' },
  { code: 'ye', name: 'Yemen', flag: 'ye' },
  { code: 'tr', name: 'Turkey', flag: 'tr' },
  { code: 'ge', name: 'Georgia', flag: 'ge' },
  { code: 'am', name: 'Armenia', flag: 'am' },
  { code: 'az', name: 'Azerbaijan', flag: 'az' },
  { code: 'ru', name: 'Russia', flag: 'ru' },
  { code: 'ua', name: 'Ukraine', flag: 'ua' },
  { code: 'by', name: 'Belarus', flag: 'by' },
  { code: 'md', name: 'Moldova', flag: 'md' },
  { code: 'rs', name: 'Serbia', flag: 'rs' },
  { code: 'me', name: 'Montenegro', flag: 'me' },
  { code: 'ba', name: 'Bosnia and Herzegovina', flag: 'ba' },
  { code: 'mk', name: 'North Macedonia', flag: 'mk' },
  { code: 'al', name: 'Albania', flag: 'al' },
  { code: 'xk', name: 'Kosovo', flag: 'xk' },
  { code: 'ma', name: 'Morocco', flag: 'ma' },
  { code: 'dz', name: 'Algeria', flag: 'dz' },
  { code: 'tn', name: 'Tunisia', flag: 'tn' },
  { code: 'ly', name: 'Libya', flag: 'ly' },
  { code: 'eg', name: 'Egypt', flag: 'eg' },
  { code: 'sd', name: 'Sudan', flag: 'sd' },
  { code: 'ss', name: 'South Sudan', flag: 'ss' },
  { code: 'et', name: 'Ethiopia', flag: 'et' },
  { code: 'er', name: 'Eritrea', flag: 'er' },
  { code: 'dj', name: 'Djibouti', flag: 'dj' },
  { code: 'so', name: 'Somalia', flag: 'so' },
  { code: 'ke', name: 'Kenya', flag: 'ke' },
  { code: 'ug', name: 'Uganda', flag: 'ug' },
  { code: 'tz', name: 'Tanzania', flag: 'tz' },
  { code: 'rw', name: 'Rwanda', flag: 'rw' },
  { code: 'bi', name: 'Burundi', flag: 'bi' },
  { code: 'mw', name: 'Malawi', flag: 'mw' },
  { code: 'zm', name: 'Zambia', flag: 'zm' },
  { code: 'zw', name: 'Zimbabwe', flag: 'zw' },
  { code: 'bw', name: 'Botswana', flag: 'bw' },
  { code: 'na', name: 'Namibia', flag: 'na' },
  { code: 'za', name: 'South Africa', flag: 'za' },
  { code: 'ls', name: 'Lesotho', flag: 'ls' },
  { code: 'sz', name: 'Eswatini', flag: 'sz' },
  { code: 'mz', name: 'Mozambique', flag: 'mz' },
  { code: 'mg', name: 'Madagascar', flag: 'mg' },
  { code: 'mu', name: 'Mauritius', flag: 'mu' },
  { code: 'sc', name: 'Seychelles', flag: 'sc' },
  { code: 'km', name: 'Comoros', flag: 'km' },
  { code: 'yt', name: 'Mayotte', flag: 'yt' },
  { code: 're', name: 'Réunion', flag: 're' },
  { code: 'ng', name: 'Nigeria', flag: 'ng' },
  { code: 'gh', name: 'Ghana', flag: 'gh' },
  { code: 'ci', name: 'Ivory Coast', flag: 'ci' },
  { code: 'sn', name: 'Senegal', flag: 'sn' },
  { code: 'gm', name: 'Gambia', flag: 'gm' },
  { code: 'gw', name: 'Guinea-Bissau', flag: 'gw' },
  { code: 'gn', name: 'Guinea', flag: 'gn' },
  { code: 'sl', name: 'Sierra Leone', flag: 'sl' },
  { code: 'lr', name: 'Liberia', flag: 'lr' },
  { code: 'ml', name: 'Mali', flag: 'ml' },
  { code: 'bf', name: 'Burkina Faso', flag: 'bf' },
  { code: 'ne', name: 'Niger', flag: 'ne' },
  { code: 'td', name: 'Chad', flag: 'td' },
  { code: 'cm', name: 'Cameroon', flag: 'cm' },
  { code: 'cf', name: 'Central African Republic', flag: 'cf' },
  { code: 'gq', name: 'Equatorial Guinea', flag: 'gq' },
  { code: 'ga', name: 'Gabon', flag: 'ga' },
  { code: 'cg', name: 'Republic of the Congo', flag: 'cg' },
  { code: 'cd', name: 'Democratic Republic of the Congo', flag: 'cd' },
  { code: 'ao', name: 'Angola', flag: 'ao' },
  { code: 'st', name: 'São Tomé and Príncipe', flag: 'st' },
  { code: 'cv', name: 'Cape Verde', flag: 'cv' },
  { code: 'mr', name: 'Mauritania', flag: 'mr' },
  { code: 'eh', name: 'Western Sahara', flag: 'eh' },
  { code: 'tn', name: 'Tunisia', flag: 'tn' },
  { code: 'dz', name: 'Algeria', flag: 'dz' },
  { code: 'ma', name: 'Morocco', flag: 'ma' },
  { code: 'ly', name: 'Libya', flag: 'ly' },
  { code: 'eg', name: 'Egypt', flag: 'eg' },
  { code: 'sd', name: 'Sudan', flag: 'sd' },
  { code: 'ss', name: 'South Sudan', flag: 'ss' },
  { code: 'et', name: 'Ethiopia', flag: 'et' },
  { code: 'er', name: 'Eritrea', flag: 'er' },
  { code: 'dj', name: 'Djibouti', flag: 'dj' },
  { code: 'so', name: 'Somalia', flag: 'so' },
  { code: 'ke', name: 'Kenya', flag: 'ke' },
  { code: 'ug', name: 'Uganda', flag: 'ug' },
  { code: 'tz', name: 'Tanzania', flag: 'tz' },
  { code: 'rw', name: 'Rwanda', flag: 'rw' },
  { code: 'bi', name: 'Burundi', flag: 'bi' },
  { code: 'mw', name: 'Malawi', flag: 'mw' },
  { code: 'zm', name: 'Zambia', flag: 'zm' },
  { code: 'zw', name: 'Zimbabwe', flag: 'zw' },
  { code: 'bw', name: 'Botswana', flag: 'bw' },
  { code: 'na', name: 'Namibia', flag: 'na' },
  { code: 'za', name: 'South Africa', flag: 'za' },
  { code: 'ls', name: 'Lesotho', flag: 'ls' },
  { code: 'sz', name: 'Eswatini', flag: 'sz' },
  { code: 'mz', name: 'Mozambique', flag: 'mz' },
  { code: 'mg', name: 'Madagascar', flag: 'mg' },
  { code: 'mu', name: 'Mauritius', flag: 'mu' },
  { code: 'sc', name: 'Seychelles', flag: 'sc' },
  { code: 'km', name: 'Comoros', flag: 'km' },
  { code: 'yt', name: 'Mayotte', flag: 'yt' },
  { code: 're', name: 'Réunion', flag: 're' },
  { code: 'ng', name: 'Nigeria', flag: 'ng' },
  { code: 'gh', name: 'Ghana', flag: 'gh' },
  { code: 'ci', name: 'Ivory Coast', flag: 'ci' },
  { code: 'sn', name: 'Senegal', flag: 'sn' },
  { code: 'gm', name: 'Gambia', flag: 'gm' },
  { code: 'gw', name: 'Guinea-Bissau', flag: 'gw' },
  { code: 'gn', name: 'Guinea', flag: 'gn' },
  { code: 'sl', name: 'Sierra Leone', flag: 'sl' },
  { code: 'lr', name: 'Liberia', flag: 'lr' },
  { code: 'ml', name: 'Mali', flag: 'ml' },
  { code: 'bf', name: 'Burkina Faso', flag: 'bf' },
  { code: 'ne', name: 'Niger', flag: 'ne' },
  { code: 'td', name: 'Chad', flag: 'td' },
  { code: 'cm', name: 'Cameroon', flag: 'cm' },
  { code: 'cf', name: 'Central African Republic', flag: 'cf' },
  { code: 'gq', name: 'Equatorial Guinea', flag: 'gq' },
  { code: 'ga', name: 'Gabon', flag: 'ga' },
  { code: 'cg', name: 'Republic of the Congo', flag: 'cg' },
  { code: 'cd', name: 'Democratic Republic of the Congo', flag: 'cd' },
  { code: 'ao', name: 'Angola', flag: 'ao' },
  { code: 'st', name: 'São Tomé and Príncipe', flag: 'st' },
  { code: 'cv', name: 'Cape Verde', flag: 'cv' },
  { code: 'mr', name: 'Mauritania', flag: 'mr' },
  { code: 'eh', name: 'Western Sahara', flag: 'eh' },
]

/**
 * Format countries for use in Select components
 *
 * @returns Array of SelectOption objects with value and label properties
 */
export function getCountriesForSelect() {
  return COUNTRIES.map((country) => ({
    value: country.code,
    label: country.name,
  }))
}

/**
 * Format countries for use in Select components with flags
 *
 * @returns Array of SelectOption objects with value, label, and image properties
 */
export function getCountriesForSelectWithFlags() {
  return COUNTRIES.map((country) => ({
    value: country.code,
    label: country.name,
    image: `/images/flags/${country.flag}.svg`,
  }))
}

/**
 * Get country by code
 *
 * @param code - The country code
 * @returns The country object or undefined if not found
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code.toLowerCase())
}
